name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

permissions:
  contents: read

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@d048c9245c93c10c06d42d1ea9311fcd3d416530 # main
        with:
          repository: openstack/cinder
          ref: e4a83e9391c7441bfcd6f551d905fd1f0bcb418a # master

      - uses: step-security/setup-qemu-action@1d653f731ddc90c553742100d15205c94b792314 # v4.2.0

      - uses: step-security/setup-buildx-action@a4709e2865773e1792246433e8eb922f9743a875 # v4.2.0

      - uses: step-security/docker-login-action@8c7b695d8738c5699a679ff5254baf0f19f20a94 # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        id: meta
        with:
          images: ghcr.io/vexxhost/docker-cinder-2026.2
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix=
            type=ref,event=branch
            type=match,pattern=stable/(.*),group=1,value={{branch}}
            type=ref,event=pr

      - uses: step-security/docker-build-push-action@144392094f7fc3199dda455efe3b70dbea4b72a0 # v7.3.0
        id: build
        with:
          context: .
          build-contexts: cinder=openstack/cinder
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: ubie-oss/comment-to-merged-pr-action@947981079c7889504e28088fb38649bc5218e28d # v0.4.0
        if: github.event_name != 'pull_request'
        with:
          github-token: ${{ github.token }}
          message: |-
            This pull request has been included in the following image tags:

            ```
            ${{ steps.meta.outputs.tags }}
            ```

            **Digest:** `ghcr.io/vexxhost/docker-cinder-2026.2@${{ steps.build.outputs.digest }}`
